spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console:
    enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        user_sql_comments: true
    hibernate:
      ddl-auto: create
  profiles:
    active: local
    include: secret

  servlet.multipart.max-file-size: 5MB
  servlet.multipart.max-request-size: 5MB