spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true

    hibernate:
      ddl-auto: create
  profiles:
    active: local
    include: secret